asyncapi: 3.0.0
info:
  title: Flux Interface Contract
  version: 1.0.0
  description: |
    Minimal conversational speech recognition scaffolding for Deepgram starter applications.
    Stream live audio from URLs, get real-time turn-based transcripts via WebSocket using Flux.
  contact:
    email: devrel@deepgram.com
    url: https://community.deepgram.com
    name: Deepgram Developer Relations
  license:
    name: Privacy Notice
    url: https://deepgram.com/privacy/
  externalDocs:
    description: Visit our docs to learn more about using Deepgram APIs
    url: https://developers.deepgram.com
servers:
  starter-app:
    host: "{host}:{port}"
    protocol: wss
    description: Starter app development server
    security:
      - $ref: "#/components/securitySchemes/ApiKeyAuth"
components:
  securitySchemes:
    ApiKeyAuth:
      type: httpApiKey
      in: header
      name: Authorization
      description: API key authentication (handled by starter app proxy)
  operationTraits:
    AuthTrait:
      security:
        - $ref: "#/components/securitySchemes/ApiKeyAuth"
  schemas:
    StreamUrl:
      type: string
      format: uri
      description: URL of live audio stream to transcribe
      examples:
        - http://stream.live.vc.bbcmedia.co.uk/bbc_world_service
    Model:
      type: string
      description: Flux model to use for conversational transcription
      default: flux-general-en
      enum:
        - flux-general-en
      examples:
        - flux-general-en
    ConnectedEvent:
      type: object
      description: Connection established event
      required:
        - type
        - request_id
        - sequence_id
      properties:
        type:
          type: string
          enum: [Connected]
          description: Message type identifier
        request_id:
          type: string
          format: uuid
          description: Unique request identifier
        sequence_id:
          type: number
          description: Sequence number starting at 0
    TurnInfoEvent:
      type: object
      description: Turn-based transcription information with end-of-turn detection
      required:
        - type
        - request_id
        - sequence_id
        - event
        - turn_index
        - audio_window_start
        - audio_window_end
        - transcript
        - words
        - end_of_turn_confidence
      properties:
        type:
          type: string
          enum: [TurnInfo]
          description: Message type identifier
        request_id:
          type: string
          format: uuid
          description: Unique request identifier
        sequence_id:
          type: number
          description: Sequence number incremented for each message
        event:
          type: string
          enum:
            - Update
            - StartOfTurn
            - EndOfTurn
          description: Type of turn event (Update, StartOfTurn, EndOfTurn)
        turn_index:
          type: number
          description: Index of the current turn
        audio_window_start:
          type: number
          description: Start time in seconds
        audio_window_end:
          type: number
          description: End time in seconds
        transcript:
          type: string
          description: Transcribed text for the turn
        words:
          type: array
          description: Word-level information
          items:
            type: object
            required:
              - word
              - confidence
            properties:
              word:
                type: string
                description: Individual word from transcript
              confidence:
                type: number
                description: Confidence score (0-1)
        end_of_turn_confidence:
          type: number
          description: Confidence that no more speech is coming (0-1)
    ErrorEvent:
      type: object
      description: Error event
      required:
        - type
        - error
      properties:
        type:
          type: string
          enum: [Error]
          description: Message type identifier
        error:
          type: object
          required:
            - type
            - code
            - message
          properties:
            type:
              type: string
              description: Error category
            code:
              type: string
              enum:
                - INVALID_STREAM_URL
                - STREAM_UNREACHABLE
                - MODEL_NOT_FOUND
                - CONNECTION_FAILED
                - AUDIO_FORMAT_ERROR
              description: Machine-readable error code
            message:
              type: string
              description: Human-readable error message
            details:
              type: object
              description: Additional error context
              additionalProperties: true
    AudioData:
      type: string
      format: binary
      description: Containerized audio data from live stream
      contentType: application/octet-stream
  messages:
    AudioDataMessage:
      name: AudioDataMessage
      title: Audio Data
      description: Containerized audio chunks from live stream
      contentType: application/octet-stream
      payload:
        $ref: "#/components/schemas/AudioData"
    ConnectedEventMessage:
      name: ConnectedEventMessage
      title: Connected Event
      description: Connection established confirmation
      contentType: application/json
      payload:
        $ref: "#/components/schemas/ConnectedEvent"
    TurnInfoEventMessage:
      name: TurnInfoEventMessage
      title: Turn Info Event
      description: Real-time turn-based transcription with end-of-turn detection
      contentType: application/json
      payload:
        $ref: "#/components/schemas/TurnInfoEvent"
    ErrorEventMessage:
      name: ErrorEventMessage
      title: Error Event
      description: Error information
      contentType: application/json
      payload:
        $ref: "#/components/schemas/ErrorEvent"
channels:
  FluxStream:
    address: /flux/stream
    description: Conversational speech recognition with turn detection via WebSocket
    bindings:
      ws:
        query:
          type: object
          required:
            - stream_url
            - model
          properties:
            stream_url:
              $ref: "#/components/schemas/StreamUrl"
            model:
              $ref: "#/components/schemas/Model"
    messages:
      AudioData:
        $ref: "#/components/messages/AudioDataMessage"
      ConnectedEvent:
        $ref: "#/components/messages/ConnectedEventMessage"
      TurnInfoEvent:
        $ref: "#/components/messages/TurnInfoEventMessage"
      ErrorEvent:
        $ref: "#/components/messages/ErrorEventMessage"
operations:
  ConnectToStream:
    action: send
    channel:
      $ref: "#/channels/FluxStream"
    description: Connect to Flux stream with audio URL
    traits:
      - $ref: "#/components/operationTraits/AuthTrait"
    messages:
      - $ref: "#/channels/FluxStream/messages/AudioData"
  ReceiveConnected:
    action: receive
    channel:
      $ref: "#/channels/FluxStream"
    description: Receive connection confirmation
    traits:
      - $ref: "#/components/operationTraits/AuthTrait"
    messages:
      - $ref: "#/channels/FluxStream/messages/ConnectedEvent"
  ReceiveTurnInfo:
    action: receive
    channel:
      $ref: "#/channels/FluxStream"
    description: Receive real-time turn-based transcription updates
    traits:
      - $ref: "#/components/operationTraits/AuthTrait"
    messages:
      - $ref: "#/channels/FluxStream/messages/TurnInfoEvent"
  ReceiveError:
    action: receive
    channel:
      $ref: "#/channels/FluxStream"
    description: Receive error events from the Flux stream
    traits:
      - $ref: "#/components/operationTraits/AuthTrait"
    messages:
      - $ref: "#/channels/FluxStream/messages/ErrorEvent"
